{% set version = "1.4.4" %}
package:
    name: clef
    version: {{ version }}



build:
    number: 1

source:
    path: ../.

build:
    noarch: python
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"
    script_env:
        - LC_ALL # For click tests
        - CLEF_DB
    entry_points:
        - clef = clef.cli:clef_catch

requirements:
    host:
        - python
        - pip
        - pbr
    run:
        - python
        - six
        - sqlalchemy
        - psycopg2
        - requests
        - click
        - mock # [py27]
        - beautifulsoup4
        - lxml
        - pandas

about:
    home: https://github.com/coecms/clef
    license: Apache 2.0
    license_file: LICENSE-2.0.txt
    summary: 'CleF queries ESGF data at NCI' 
