REFRESH MATERIALIZED VIEW CONCURRENTLY esgf_paths;
REFRESH MATERIALIZED VIEW CONCURRENTLY c5_metadata_dataset_link;
REFRESH MATERIALIZED VIEW CONCURRENTLY c6_metadata_dataset_link;
REFRESH MATERIALIZED VIEW CONCURRENTLY cmip5_dataset;
REFRESH MATERIALIZED VIEW CONCURRENTLY cmip6_dataset;
REFRESH MATERIALIZED VIEW CONCURRENTLY extended_metadata;
REFRESH MATERIALIZED VIEW CONCURRENTLY checksums;
