REFRESH MATERIALIZED VIEW CONCURRENTLY esgf_paths;
REFRESH MATERIALIZED VIEW CONCURRENTLY checksums;
REFRESH MATERIALIZED VIEW CONCURRENTLY esgf_metadata_dataset_link;
REFRESH MATERIALIZED VIEW CONCURRENTLY esgf_dataset;
REFRESH MATERIALIZED VIEW CONCURRENTLY extended_metadata;
