REFRESH MATERIALIZED VIEW esgf_paths;
REFRESH MATERIALIZED VIEW checksums;
REFRESH MATERIALIZED VIEW esgf_metadata_dataset_link;
REFRESH MATERIALIZED VIEW esgf_dataset;
REFRESH MATERIALIZED VIEW extended_metadata;
